on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: octo-sts/action
      id: octo-sts
      with:
        scope: imjasonh/workflow-private
        identity: workflow-public
    - env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        gh workflow run -R imjasonh/workflow-private private.yaml
