on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: octo-sts/action@v1.0.0
      id: octo-sts
      with:
        scope: imjasonh/workflow-private
        identity: workflow-public
    - uses: imjasonh/workflow-public@v1.2.3
    
