on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: octo-sts/action@v1.0.0
      id: octo-sts
      with:
        scope: imjasonh/workflow-private
        identity: workflow-public
    - env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        gh workflow run --repo imjasonh/workflow-private private.yaml --ref main

        # HACK: watch any recent ongoing runs, and fail if any of those fail.
        gh run watch -R imjasonh/workflow-private --exit-status

        # LESS HACKY: list recent runs of private.yaml, get their number, and watch just those runs
        #num=$(gh run list --repo imjasonh/workflow-private -w private.yaml -e workflow_dispatch --json number --jq '.[].number')
        #gh run watch --repo imjasonh/workflow-private --exit-status ${num}
