on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: octo-sts/action@v1.0.0
      id: octo-sts
      with:
        scope: imjasonh/workflow-private
        identity: workflow-public
    - env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        now=$(date +"%Y-%m-%dT%H:%M:%S%:z")
        gh workflow run --repo imjasonh/workflow-private private.yaml --ref main

        num=$(gh run list --repo imjasonh/workflow-private -w private.yaml -e workflow_dispatch --created ">${now}" --json number --jq '.[0].number')
        echo "num: $num"
        while true; do
          status=$(gh run list --repo imjasonh/workflow-private -w private.yaml --json number,status | jq --arg num "$num" -r '.[] | select(.number == $num) | .status')
          echo "status: $status"
          if [ "$status" = "completed" ]; then
            break
          fi
          sleep 5
        done
